a

diff --git a/sample-app/Jenkinsfile b/sample-app/Jenkinsfile
--- a/sample-app/Jenkinsfile
+++ b/sample-app/Jenkinsfile
@@ -244,27 +244,26 @@ def installComponent( componentName, closure) {
             remote.passphrase = SSH_KEY_PASSPHRASE
 
             // SSH into the remote server and execute the bash script
-            def remoteCommand = exportedValues + 'bash $COMPONENT_SCRIPTS_DIR/liveness-check.sh'
-            def sshResult = sshCommand remote: remote, command: remoteCommand
-            echo "Result: " + sshResult
+            def remoteCommand = exportedValues + '''
+# Check if the script file exists
+if [ -f "$COMPONENT_SCRIPTS_DIR/liveness-check.sh" ]; then
+  # Execute the script and capture the exit status
+  bash -xeuo "$COMPONENT_SCRIPTS_DIR/liveness-check.sh"
+  exit_status=$?
 
-            // Check the exit status of the SSH command
-            if (sshResult.status == 0) {
-                error "Error executing SSH script. Job will be stopped."
-            } else {
-                echo "Checked successfully."
-            }
+  # Check if the exit status is 0
+  if [ $exit_status -eq 0 ]; then
+    echo "Script executed successfully."
+  else
+    echo "Script execution failed with exit status $exit_status."
+    exit 1
+  fi
+else
+  echo "Script file not found."
+fi
 
-            remoteCommand = exportedValues + 'bash $DOWNLOAD_DEPLOY_DIR/install.sh'
-            
-            sshResult = sshCommand remote: remote, command: remoteCommand
-            echo "Result: " + sshResult
-             // Check the exit status of the SSH command
-            if (sshResult.status == 0) {
-                echo "SSH script executed successfully."
-            } else {
-                error "Error executing SSH script. Job will be stopped."
-            }
+bash -xeuo "$DOWNLOAD_DEPLOY_DIR/install.sh"'
+            '''
 
             if(closure){
                 def commandExecutor = { cmd, outputToFilename ->
