a

diff --git a/sample-app/Jenkinsfile b/sample-app/Jenkinsfile
--- a/sample-app/Jenkinsfile
+++ b/sample-app/Jenkinsfile
@@ -250,7 +250,7 @@ def downloadComponent( componentName, closure) {
         sh "curl -o ${componentSnapshot.name}.zip ${componentSnapshot.artifact_path}"
         
         def platformEnv = exportPlatformEnvironmentVariables(componentSnapshot, hostYaml, mergedPropsYaml) 
-        def exportedValues = platformEnv.exportedValues + "\n"
+        def exportedValues = platformEnv.exportedValues
         def variables = platformEnv.variables
 
         sshWrapper(targetComponentName, componentSnapshot, hostYaml, componentYaml, targetFolder){ remote ->
@@ -263,29 +263,30 @@ def downloadComponent( componentName, closure) {
                 destination = variables.DOWNLOAD_DEPLOY_DIR
             }
 
-            def result = sshCommand remote: remote, command: 
-            "sudo mkdir -p ${destination} " +
-            "sudo mkdir -p ${destination}/raw " +
-            "sudo rm -rf ${destination} " +
-            "sudo chown ${variables.APP_SERVICE_ACCOUNT}:${variables.APP_SERVICE_ACCOUNT_GROUP} ${destination}" +
-            "sudo chmod 755 ${destination}"
+            def result = sshCommand remote: remote, command: """
+                sudo mkdir -p ${destination}
+                sudo mkdir -p ${destination}/raw
+                sudo rm -rf ${destination}
+                sudo chown ${variables.APP_SERVICE_ACCOUNT}:${variables.APP_SERVICE_ACCOUNT_GROUP} ${destination}
+                sudo chmod 755 ${destination}
+            """
             
             sshPut remote: remote, from: "${componentSnapshot.name}.zip", into: "${destination}/raw/."
             
-            sshCommand remote: remote, command: 
-            "cd ${destination}\n" +
-            "file=raw/${componentSnapshot.name}.zip\n" + 
-            '''
-            if [[ $(file -b --mime-type "$file") == application/gzip ]]; then
-                tar -xzf "$file" -C .
-            elif [[ $(file -b --mime-type "$file") == application/x-tar ]]; then
-                tar -xf "$file" -C .
-            elif [[ $(file -b --mime-type "$file") == application/zip ]]; then
-                unzip "$file" -d .
-            else
-                echo "Unknown file format: $file"
-            fi
-            '''
+            sshCommand remote: remote, command: """
+                cd ${destination}
+                file=raw/${componentSnapshot.name}.zip
+                
+                if [[ \$(file -b --mime-type "\$file") == application/gzip ]]; then
+                    tar -xzf "\$file" -C .
+                elif [[ \$(file -b --mime-type "\$file") == application/x-tar ]]; then
+                    tar -xf "\$file" -C .
+                elif [[ \$(file -b --mime-type "\$file") == application/zip ]]; then
+                    unzip "\$file" -d .
+                else
+                    echo "Unknown file format: \$file"
+                fi
+            """
 
             if(closure){
                 closure(remote, variables, targetComponentName, componentSnapshot, hostYaml, componentYaml, targetFolder)
@@ -306,39 +307,40 @@ def installComponent( componentName, closure) {
         archiveArtifacts artifacts: yamlFilename
 
         def platformEnv = exportPlatformEnvironmentVariables(componentSnapshot, hostYaml, mergedPropsYaml) 
-        def exportedValues = platformEnv.exportedValues + "\n"
+        def exportedValues = platformEnv.exportedValues
         def variables = platformEnv.variables
         //call liveness check
         //call install.sh
        sshWrapper(targetComponentName, componentSnapshot, hostYaml, componentYaml, targetFolder){ remote ->
             // SSH into the remote server and execute the bash script
 
-            def result = sshCommand remote: remote, command: 
-            "sudo mkdir -p ${variables.COMPONENT_BINARY_DIR} " +
-            "sudo mkdir -p ${variables.COMPONENT_SCRIPTS_DIR} "
+            def result = sshCommand remote: remote, command: """
+                sudo mkdir -p ${variables.COMPONENT_BINARY_DIR}
+                sudo mkdir -p ${variables.COMPONENT_SCRIPTS_DIR}
+            """
 
-            
-            result = sshCommand remote: remote, command: exportedValues + '''
-# Check if the script file exists
-if [ -f "$COMPONENT_SCRIPTS_DIR/liveness-check.sh" ]; then
-  # Execute the script and capture the exit status
-  bash -x "$COMPONENT_SCRIPTS_DIR/liveness-check.sh"
-  exit_status=$?
+            result = sshCommand remote: remote, command: """
+                ${exportedValues}
+                # Check if the script file exists
+                if [ -f "\$COMPONENT_SCRIPTS_DIR/liveness-check.sh" ]; then
+                    # Execute the script and capture the exit status
+                    bash -x "\$COMPONENT_SCRIPTS_DIR/liveness-check.sh"
+                    exit_status=\$?
 
-  # Check if the exit status is 0
-  if [ $exit_status -eq 0 ]; then
-    echo "Script executed successfully."
-    exit 1
-  else
-    echo "Script execution failed with exit status $exit_status."
-  fi
-else
-  echo "Script file not found."
-fi
+                    # Check if the exit status is 0
+                    if [ \$exit_status -eq 0 ]; then
+                        echo "Script executed successfully."
+                        exit 1
+                    else
+                        echo "Script execution failed with exit status \$exit_status."
+                    fi
+                else
+                    echo "Script file not found."
+                fi
 
-bash -x "$DOWNLOAD_DEPLOY_DIR/scripts/install.sh"
-bash -x "$DOWNLOAD_DEPLOY_DIR/scripts/enable-linux-services.sh"
-            '''
+                bash -x "\$DOWNLOAD_DEPLOY_DIR/scripts/install.sh"
+                bash -x "\$DOWNLOAD_DEPLOY_DIR/scripts/enable-linux-services.sh"
+            """
 
             if(closure){
                 
